FROM ghcr.io/lehigh-university-libraries/scyllaridae:main@sha256:a9f8d04a3695f0de44fbb0c5c63aac3235bcbf23b6fb6d3f5ecd1f7915aae92f

ENV \
  FITS_URI=http://fits:8080/fits/examine

COPY scyllaridae.yml /app/scyllaridae.yml
