FROM ghcr.io/lehigh-university-libraries/scyllaridae:main@sha256:17b3ea02586a752473d42920b9098b9e8e395fde37b498d41e904e29c4e51353

ENV \
  FITS_URI=http://fits:8080/fits/examine

COPY scyllaridae.yml /app/scyllaridae.yml
