FROM ghcr.io/lehigh-university-libraries/scyllaridae:main@sha256:e962c522e49dd48afc11792b89505895ab29a37044ea95591881e299f856c27e

ENV \
  FITS_URI=http://fits:8080/fits/examine

COPY scyllaridae.yml /app/scyllaridae.yml
